nome =str(input('Digite o nome do aluno(a):'))
n1 = float(input('Digite a primeira nota:'))
n2 = float(input('Digite a segunda nota:'))
s = ((n1+n2)/2)
print('A media do aluno(a) {},é igual a {}'.format(nome, s))
